title:            Guan Yue (Yuma) Wu
description:      Yuma's Academic Website
# Your site's domain goes here. Leave localhost server or blank when working locally.
url:              https://yuma-wu.github.io

# Owner/author information
owner:
  name:           Guan Yue (Yuma) Wu
  avatar:         yuma.jpg
  bio:            I'm a PhD student at the University of Ottawa with a background in computer science and law.
                  My research is focused on the impact of artificial sociality and regulation thereof -- robot girlfriends, AI chatbots, that sort of thing.
  email:          yuma.wu@uottawa.ca
  # Social networking links are used in author-bio sidebar. Update and remove as you like.
  orcid: 0009-0001-4922-9637
  github: yuma-wu
# Analytics and webmaster tools stuff goes here
google_analytics: 
# UA-19657956-3
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in top navigation
# For external links add external: true
links:
  - title: About
    url: "/"
  - title: CV
    url: "/cv/"
  - title: Research
    url: "/research/"
  - title: Teaching
    url: "/teaching/"
  - title: Blog
    url: "/blog/"
  - title: Resources
    url: "/resources/"
  - title: Fun
    url: "/fun/"

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/Toronto
future:      true
#pygments:    true
highlighter: rouge
markdown:    kramdown
kramdown:
  extensions: ["strikethrough"]
  
# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:year/:title/

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
#  enable_coderay: false

#  coderay:
#    coderay_line_numbers:
#    coderay_line_numbers_start: 1
#    coderay_tab_width: 4
#    coderay_bold_every: 10
#    coderay_css: class

include: ["_pages"]
exclude: ["Gemfile", "Gemfile.lock", "README.md", "CNAME"]
